version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: product
        identifier: raw_gz_product
        description: products of greenweez
        columns:
          - name: products_id
            description: primary key
            tests:
              - unique
              - not_null

      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
        freshness:
          warn_after:
            count: 90
            period: day

      - name: ship
        identifier: raw_gz_ship
        description: shipping of greenweez
        columns:
          - name: orders_id
            description: primary key
            tests:
              - unique
              - not_null

      - name: adwords
        identifier: raw_gz_adwords
        description: data of adwords ads
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key || '-' || camPGN_name)"
          - not_null:
              column_name:
              - date_date
              - paid_source
              - campaign_key
              - camPGN_name
              - ads_cost
              - impression
              - click

      - name: bing
        identifier: raw_gz_bing
        description: data of bing ads
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key || '-' || camPGN_name)"
          - not_null:
              column_name:
              - date_date
              - paid_source
              - campaign_key
              - camPGN_name
              - ads_cost
              - impression
              - click

      - name: criteo
        identifier: raw_gz_criteo
        description: data of criteo ads
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key || '-' || camPGN_name)"
          - not_null:
              column_name:
              - date_date
              - paid_source
              - campaign_key
              - camPGN_name
              - ads_cost
              - impression
              - click

      - name: facebook
        identifier: raw_gz_facebook
        description: data of facebook ads
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key || '-' || camPGN_name)"
          - not_null:
              column_name:
              - date_date
              - paid_source
              - campaign_key
              - camPGN_name
              - ads_cost
              - impression
              - click

models:
  - name: stg_raw__sales
  - name: stg_raw__product
  - name: stg_raw__ship
  - name: int_sales_margin
    tests:
      - unique:
          column_name: "(orders_id || '-' || products_id)"
      - not_null:
          column_name:
            - orders_id
            - products_id
            - margin
            - purchase_cost
            - purchase_price
            - date_date
            - revenue
            - quantity
  - name: int_orders_operational
  - name: finance_days
  - name: int_campaigns
    description: data of aggregated costs of all the campaigns
  - name: int_campaigns_day
    description: data of aggregated version of int_campaigns model for each day
  - name: finance_campaigns_day
    description: data of aggregated version of int_campaigns_day model for each day including ads_margin
  - name: finance_campaigns_month
    description: data of aggregated version of finance_campaigns_day model for each month
